In [1]:
#Import the required packages
#Import package pandas for data analysis
import pandas as pd

In [2]:
def build_dqr_table(df, columns):
    """
    Build and save a Data Quality Report table.
    
    Parameters:
    -----------
    df : pandas.DataFrame
    columns : Index
        Features to include
    csv_filename : str
        Output filename
    
    Returns:
    --------
    pandas.DataFrame
        Complete DQR table
    """
    stats = df[columns].describe().T
    perc_missing = 100 * (df[columns].isnull().sum() / len(df))
    cardinality = df[columns].nunique()
    
    dqr_table = pd.concat([
        stats,
        pd.DataFrame(perc_missing, columns=['%missing']),
        pd.DataFrame(cardinality, columns=['cardinality'])
    ], axis=1)
    
    return dqr_table


print("✓ Helper function loaded successfully")

✓ Helper function loaded successfully

In [3]:
def load_data(filename):
    # Reading from a csv file, into a data frame with error handling
    try:
        # If the csv file has any special symbols, it helps to specify the file encoding.
        df = pd.read_csv(filename, 
                        keep_default_na=True, 
                        delimiter=',', 
                        skipinitialspace=True)
        
        print(f"✓ Successfully loaded dataset with {df.shape[0]} rows and {df.shape[1]} columns")
        
        # Show the first few rows in the data frame
        display(df.head(5))
        
    except FileNotFoundError:
        print("ERROR: The file 'ppr-group-25204989-train.csv' was not found.")
        print("Please ensure the file is in the current working directory.")
    except Exception as e:
        print(f"ERROR: An unexpected error occurred: {e}")

    return df

In [4]:
# Validate that the dataframe has data and expected columns
def validate_data(df):
    print("Dataset Validation Checks:")
    print("="*60)

    # Check 1: Dataset is not empty
    if df.empty:
        print("⚠ WARNING: Dataset is empty!")
    else:
        print(f"✓ Dataset contains {df.shape[0]:,} rows")

    # Check 2: Check for duplicate rows
    duplicate_count = df.duplicated().sum()
    if duplicate_count > 0:
        print(f"⚠ WARNING: Found {duplicate_count} duplicate rows")
    else:
        print("✓ No duplicate rows found")

    # Check 3: Check if all columns are unnamed
    unnamed_cols = [col for col in df.columns if 'Unnamed' in str(col)]
    if unnamed_cols:
        print(f"⚠ WARNING: Found {len(unnamed_cols)} unnamed columns: {unnamed_cols}")
    else:
        print("✓ All columns have names")

    # Check 4: Basic column overview
    print(f"\n✓ Dataset has {df.shape[1]} columns:")
    print(f"  - Column names: {list(df.columns)}")

## 1. ALF01.csv

In [5]:
df=load_data("QLF50.csv")

✓ Successfully loaded dataset with 5940 rows and 12 columns

,STATISTIC,Statistic Label,TLIST(Q1),Quarter,C02199V02655,Sex,C04283V05060,Education Attainment Level,C02076V02508,Age Group,UNIT,VALUE
0,QLF50C01,Employment rate,20191,2019Q1,-,Both sexes,-,Levels of Education (Levels 0-8),-,All ages,%,74.9
1,QLF50C01,Employment rate,20191,2019Q1,-,Both sexes,-,Levels of Education (Levels 0-8),365,20 - 24 years,%,64.0
2,QLF50C01,Employment rate,20191,2019Q1,-,Both sexes,-,Levels of Education (Levels 0-8),410,25 - 29 years,%,80.1
3,QLF50C01,Employment rate,20191,2019Q1,-,Both sexes,-,Levels of Education (Levels 0-8),4251,25 - 54 years,%,80.1
4,QLF50C01,Employment rate,20191,2019Q1,-,Both sexes,-,Levels of Education (Levels 0-8),440,30 - 34 years,%,81.4

In [6]:
validate_data(df)

Dataset Validation Checks:
============================================================
✓ Dataset contains 5,940 rows
✓ No duplicate rows found
✓ All columns have names

✓ Dataset has 12 columns:
  - Column names: ['STATISTIC', 'Statistic Label', 'TLIST(Q1)', 'Quarter', 'C02199V02655', 'Sex', 'C04283V05060', 'Education Attainment Level', 'C02076V02508', 'Age Group', 'UNIT', 'VALUE']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5940 entries, 0 to 5939
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   STATISTIC                   5940 non-null   object
 1   Statistic Label             5940 non-null   object
 2   TLIST(Q1)                   5940 non-null   int64
 3   Quarter                     5940 non-null   object
 4   C02199V02655                5940 non-null   object
 5   Sex                         5940 non-null   object
 6   C04283V05060                5940 non-null   object
 7   Education Attainment Level  5940 non-null   object
 8   C02076V02508                5940 non-null   object
 9   Age Group                   5940 non-null   object
 10  UNIT                        5940 non-null   object
 11  VALUE                       3968 non-null   float64
dtypes: float64(1), int64(1), object(10)
memory usage: 557.0+ KB

In [9]:


# Convert all object columns to categorical
for col in df.select_dtypes('object').columns:
    df[col] = df[col].astype('category')

df['TLIST(Q1)']=df['TLIST(Q1)'].astype('category')


# Update column groups after type corrections
numeric_columns = df.select_dtypes(['int64', 'float64']).columns
category_columns = df.select_dtypes('category').columns

print("✓ Data types corrected:")
print(f"  - Numeric features: {len(numeric_columns)}")
print(f"  - Categorical features: {len(category_columns)}")

✓ Data types corrected:
  - Numeric features: 1
  - Categorical features: 11

In [10]:
df_numeric_dqr = build_dqr_table(df, numeric_columns)
display(df_numeric_dqr)

,count,mean,std,min,25%,50%,75%,max,%missing,cardinality
VALUE,3968.0,74.122077,13.849446,26.9,66.0,76.7,85.0,97.7,33.198653,603

In [11]:
df_categorical_dqr = build_dqr_table(df, category_columns)
display(df_categorical_dqr)

,count,unique,top,freq,%missing,cardinality
STATISTIC,5940,1,QLF50C01,5940,0.0,1
Statistic Label,5940,1,Employment rate,5940,0.0,1
TLIST(Q1),5940,30,20191,198,0.0,30
Quarter,5940,30,2019Q1,198,0.0,30
C02199V02655,5940,3,-,1980,0.0,3
Sex,5940,3,Both sexes,1980,0.0,3
C04283V05060,5940,6,-,990,0.0,6
Education Attainment Level,5940,6,Less than primary (Level 0),990,0.0,6
C02076V02508,5940,11,-,540,0.0,11
Age Group,5940,11,20 - 24 years,540,0.0,11
UNIT,5940,1,%,5940,0.0,1

In [12]:
# Count each value in every categorical column, including missing values.
for col in category_columns:
    counts = (
        df[col]
        .value_counts(dropna=False)
        .rename_axis("value")
        .reset_index(name="count")
    )

    print(f"\n{col}")
    display(counts)

STATISTIC

      value  count
0  QLF50C01   5940

Statistic Label

             value  count
0  Employment rate   5940

TLIST(Q1)

    value  count
0   20191    198
1   20192    198
2   20261    198
3   20254    198
4   20253    198
5   20252    198
6   20251    198
7   20244    198
8   20243    198
9   20242    198
10  20241    198
11  20234    198
12  20233    198
13  20232    198
14  20231    198
15  20224    198
16  20223    198
17  20222    198
18  20221    198
19  20214    198
20  20213    198
21  20212    198
22  20211    198
23  20204    198
24  20203    198
25  20202    198
26  20201    198
27  20194    198
28  20193    198
29  20262    198

Quarter

     value  count
0   2019Q1    198
1   2019Q2    198
2   2026Q1    198
3   2025Q4    198
4   2025Q3    198
5   2025Q2    198
6   2025Q1    198
7   2024Q4    198
8   2024Q3    198
9   2024Q2    198
10  2024Q1    198
11  2023Q4    198
12  2023Q3    198
13  2023Q2    198
14  2023Q1    198
15  2022Q4    198
16  2022Q3    198
17  2022Q2    198
18  2022Q1    198
19  2021Q4    198
20  2021Q3    198
21  2021Q2    198
22  2021Q1    198
23  2020Q4    198
24  2020Q3    198
25  2020Q2    198
26  2020Q1    198
27  2019Q4    198
28  2019Q3    198
29  2026Q2    198

C02199V02655

  value  count
0     -   1980
1     1   1980
2     2   1980

Sex

        value  count
0  Both sexes   1980
1      Female   1980
2        Male   1980

C04283V05060

  value  count
0     -    990
1    10    990
2    20    990
3    30    990
4    40    990
5    99    990

Education Attainment Level

                                               value  count
0                        Less than primary (Level 0)    990
1                    Level of education - not stated    990
2                  Levels of Education (Levels  0-8)    990
3  Primary and lower secondary education (Levels ...    990
4                    Tertiary education (Levels 5-8)    990
5  Upper secondary and post-secondary non-tertiar...    990

C02076V02508

   value  count
0      -    540
1    365    540
2    410    540
3   4251    540
4    440    540
5    460    540
6    475    540
7    495    540
8    515    540
9    530    540
10   550    540

Age Group

            value  count
0   20 - 24 years    540
1   25 - 29 years    540
2   25 - 54 years    540
3   30 - 34 years    540
4   35 - 39 years    540
5   40 - 44 years    540
6   45 - 49 years    540
7   50 - 54 years    540
8   55 - 59 years    540
9   60 - 64 years    540
10       All ages    540

UNIT

  value  count
0     %   5940

In [13]:
for col in category_columns:
    missing_stats = (
        df.groupby(col, observed=True, dropna=False)["VALUE"]
        .agg(
            total_rows="size",
            valid_rows="count",
        )
    )

    missing_stats["missing_rows"] = (
        missing_stats["total_rows"] - missing_stats["valid_rows"]
    )
    missing_stats["missing_pct"] = (
        missing_stats["missing_rows"]
        .div(missing_stats["total_rows"])
        .mul(100)
        .round(2)
    )

    print(f"\n{col}")
    display(missing_stats.sort_values("missing_pct", ascending=False))

STATISTIC

           total_rows  valid_rows  missing_rows  missing_pct
STATISTIC
QLF50C01         5940        3968          1972         33.2

Statistic Label

                 total_rows  valid_rows  missing_rows  missing_pct
Statistic Label
Employment rate        5940        3968          1972         33.2

TLIST(Q1)

           total_rows  valid_rows  missing_rows  missing_pct
TLIST(Q1)
20261             198         125            73        36.87
20212             198         127            71        35.86
20251             198         127            71        35.86
20244             198         127            71        35.86
20254             198         128            70        35.35
20253             198         128            70        35.35
20221             198         129            69        34.85
20214             198         129            69        34.85
20262             198         129            69        34.85
20252             198         130            68        34.34
20223             198         130            68        34.34
20232             198         130            68        34.34
20203             198         131            67        33.84
20202             198         131            67        33.84
20231             198         131            67        33.84
20241             198         131            67        33.84
20234             198         132            66        33.33
20243             198         132            66        33.33
20242             198         132            66        33.33
20224             198         132            66        33.33
20222             198         132            66        33.33
20213             198         132            66        33.33
20233             198         133            65        32.83
20204             198         135            63        31.82
20201             198         138            60        30.30
20192             198         140            58        29.29
20211             198         141            57        28.79
20194             198         142            56        28.28
20193             198         142            56        28.28
20191             198         142            56        28.28

Quarter

         total_rows  valid_rows  missing_rows  missing_pct
Quarter
2026Q1          198         125            73        36.87
2021Q2          198         127            71        35.86
2025Q1          198         127            71        35.86
2024Q4          198         127            71        35.86
2025Q4          198         128            70        35.35
2025Q3          198         128            70        35.35
2022Q1          198         129            69        34.85
2021Q4          198         129            69        34.85
2026Q2          198         129            69        34.85
2025Q2          198         130            68        34.34
2022Q3          198         130            68        34.34
2023Q2          198         130            68        34.34
2020Q3          198         131            67        33.84
2020Q2          198         131            67        33.84
2023Q1          198         131            67        33.84
2024Q1          198         131            67        33.84
2023Q4          198         132            66        33.33
2024Q3          198         132            66        33.33
2024Q2          198         132            66        33.33
2022Q4          198         132            66        33.33
2022Q2          198         132            66        33.33
2021Q3          198         132            66        33.33
2023Q3          198         133            65        32.83
2020Q4          198         135            63        31.82
2020Q1          198         138            60        30.30
2019Q2          198         140            58        29.29
2021Q1          198         141            57        28.79
2019Q4          198         142            56        28.28
2019Q3          198         142            56        28.28
2019Q1          198         142            56        28.28

C02199V02655

              total_rows  valid_rows  missing_rows  missing_pct
C02199V02655
2                   1980        1241           739        37.32
1                   1980        1308           672        33.94
-                   1980        1419           561        28.33

Sex

            total_rows  valid_rows  missing_rows  missing_pct
Sex
Female            1980        1241           739        37.32
Male              1980        1308           672        33.94
Both sexes        1980        1419           561        28.33

C04283V05060

              total_rows  valid_rows  missing_rows  missing_pct
C04283V05060
10                   990           0           990       100.00
99                   990         306           684        69.09
20                   990         692           298        30.10
-                    990         990             0         0.00
30                   990         990             0         0.00
40                   990         990             0         0.00

Education Attainment Level

,total_rows,valid_rows,missing_rows,missing_pct
Education Attainment Level,,,,
Less than primary (Level 0),990,0,990,100.00
Level of education - not stated,990,306,684,69.09
Primary and lower secondary education (Levels 1-2),990,692,298,30.10
Levels of Education (Levels 0-8),990,990,0,0.00
Tertiary education (Levels 5-8),990,990,0,0.00
Upper secondary and post-secondary non-tertiary education (Levels 3 and 4),990,990,0,0.00

C02076V02508

              total_rows  valid_rows  missing_rows  missing_pct
C02076V02508
365                  540         273           267        49.44
410                  540         283           257        47.59
440                  540         303           237        43.89
460                  540         351           189        35.00
550                  540         361           179        33.15
530                  540         370           170        31.48
515                  540         374           166        30.74
475                  540         375           165        30.56
495                  540         378           162        30.00
-                    540         450            90        16.67
4251                 540         450            90        16.67

Age Group

               total_rows  valid_rows  missing_rows  missing_pct
Age Group
20 - 24 years         540         273           267        49.44
25 - 29 years         540         283           257        47.59
30 - 34 years         540         303           237        43.89
35 - 39 years         540         351           189        35.00
60 - 64 years         540         361           179        33.15
55 - 59 years         540         370           170        31.48
50 - 54 years         540         374           166        30.74
40 - 44 years         540         375           165        30.56
45 - 49 years         540         378           162        30.00
25 - 54 years         540         450            90        16.67
All ages              540         450            90        16.67

UNIT

      total_rows  valid_rows  missing_rows  missing_pct
UNIT
%           5940        3968          1972         33.2