In [1]:
#Import the required packages
#Import package pandas for data analysis
import pandas as pd

In [2]:
def build_dqr_table(df, columns):
    """
    Build and save a Data Quality Report table.
    
    Parameters:
    -----------
    df : pandas.DataFrame
    columns : Index
        Features to include
    csv_filename : str
        Output filename
    
    Returns:
    --------
    pandas.DataFrame
        Complete DQR table
    """
    stats = df[columns].describe().T
    perc_missing = 100 * (df[columns].isnull().sum() / len(df))
    cardinality = df[columns].nunique()
    
    dqr_table = pd.concat([
        stats,
        pd.DataFrame(perc_missing, columns=['%missing']),
        pd.DataFrame(cardinality, columns=['cardinality'])
    ], axis=1)
    
    return dqr_table


print("✓ Helper function loaded successfully")

✓ Helper function loaded successfully

In [3]:
def load_data(filename):
    # Reading from a csv file, into a data frame with error handling
    try:
        # If the csv file has any special symbols, it helps to specify the file encoding.
        df = pd.read_csv(filename, 
                        keep_default_na=True, 
                        delimiter=',', 
                        skipinitialspace=True)
        
        print(f"✓ Successfully loaded dataset with {df.shape[0]} rows and {df.shape[1]} columns")
        
        # Show the first few rows in the data frame
        display(df.head(5))
        
    except FileNotFoundError:
        print("ERROR: The file 'ppr-group-25204989-train.csv' was not found.")
        print("Please ensure the file is in the current working directory.")
    except Exception as e:
        print(f"ERROR: An unexpected error occurred: {e}")

    return df

In [4]:
# Validate that the dataframe has data and expected columns
def validate_data(df):
    print("Dataset Validation Checks:")
    print("="*60)

    # Check 1: Dataset is not empty
    if df.empty:
        print("⚠ WARNING: Dataset is empty!")
    else:
        print(f"✓ Dataset contains {df.shape[0]:,} rows")

    # Check 2: Check for duplicate rows
    duplicate_count = df.duplicated().sum()
    if duplicate_count > 0:
        print(f"⚠ WARNING: Found {duplicate_count} duplicate rows")
    else:
        print("✓ No duplicate rows found")

    # Check 3: Check if all columns are unnamed
    unnamed_cols = [col for col in df.columns if 'Unnamed' in str(col)]
    if unnamed_cols:
        print(f"⚠ WARNING: Found {len(unnamed_cols)} unnamed columns: {unnamed_cols}")
    else:
        print("✓ All columns have names")

    # Check 4: Basic column overview
    print(f"\n✓ Dataset has {df.shape[1]} columns:")
    print(f"  - Column names: {list(df.columns)}")

## 1. ALF01.csv

In [5]:
df=load_data("EHQ03.csv")

✓ Successfully loaded dataset with 130536 rows and 10 columns

,STATISTIC,Statistic Label,TLIST(Q1),Quarter,C02665V03225,Economic Sector NACE Rev 2,C02397V02888,Type of Employee,UNIT,VALUE
0,EHQ03C01,Employment,20081,2008Q1,-,All NACE economic sectors,-,All employees,Number,1767200.0
1,EHQ03C01,Employment,20081,2008Q1,-,All NACE economic sectors,1,"Managers, professionals and associated profess...",Number,549400.0
2,EHQ03C01,Employment,20081,2008Q1,-,All NACE economic sectors,2,"Clerical, sales and service employees",Number,685300.0
3,EHQ03C01,Employment,20081,2008Q1,-,All NACE economic sectors,3,"Production, transport, craft and other manual ...",Number,532600.0
4,EHQ03C01,Employment,20081,2008Q1,B,Mining and quarrying (B),-,All employees,Number,7100.0

In [6]:
validate_data(df)

Dataset Validation Checks:
============================================================
✓ Dataset contains 130,536 rows
✓ No duplicate rows found
✓ All columns have names

✓ Dataset has 10 columns:
  - Column names: ['STATISTIC', 'Statistic Label', 'TLIST(Q1)', 'Quarter', 'C02665V03225', 'Economic Sector NACE Rev 2', 'C02397V02888', 'Type of Employee', 'UNIT', 'VALUE']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130536 entries, 0 to 130535
Data columns (total 10 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   STATISTIC                   130536 non-null  object
 1   Statistic Label             130536 non-null  object
 2   TLIST(Q1)                   130536 non-null  int64
 3   Quarter                     130536 non-null  object
 4   C02665V03225                130536 non-null  object
 5   Economic Sector NACE Rev 2  130536 non-null  object
 6   C02397V02888                130536 non-null  object
 7   Type of Employee            130536 non-null  object
 8   UNIT                        130536 non-null  object
 9   VALUE                       20028 non-null   float64
dtypes: float64(1), int64(1), object(8)
memory usage: 10.0+ MB

In [8]:


# Convert all object columns to categorical
for col in df.select_dtypes('object').columns:
    df[col] = df[col].astype('category')

df['TLIST(Q1)']=df['TLIST(Q1)'].astype('category')


# Update column groups after type corrections
numeric_columns = df.select_dtypes(['int64', 'float64']).columns
category_columns = df.select_dtypes('category').columns

print("✓ Data types corrected:")
print(f"  - Numeric features: {len(numeric_columns)}")
print(f"  - Categorical features: {len(category_columns)}")

✓ Data types corrected:
  - Numeric features: 1
  - Categorical features: 9

In [9]:
df_numeric_dqr = build_dqr_table(df, numeric_columns)
display(df_numeric_dqr)

,count,mean,std,min,25%,50%,75%,max,%missing,cardinality
VALUE,20028.0,16026.49036,118669.549549,-8.27,10.1675,29.425,690.3675,2368400.0,84.657106,9656

In [10]:
df_categorical_dqr = build_dqr_table(df, category_columns)
display(df_categorical_dqr)

,count,unique,top,freq,%missing,cardinality
STATISTIC,130536,21,EHQ03C01,6216,0.0,21
Statistic Label,130536,21,Average Hourly Benefit in Kind,6216,0.0,21
TLIST(Q1),130536,74,20081,1764,0.0,74
Quarter,130536,74,2008Q1,1764,0.0,74
C02665V03225,130536,21,-,6216,0.0,21
Economic Sector NACE Rev 2,130536,21,Accommodation and food service activities (I),6216,0.0,21
C02397V02888,130536,4,-,32634,0.0,4
Type of Employee,130536,4,All employees,32634,0.0,4
UNIT,130536,3,Euro,111888,0.0,3

In [11]:
# Count each value in every categorical column, including missing values.
for col in category_columns:
    counts = (
        df[col]
        .value_counts(dropna=False)
        .rename_axis("value")
        .reset_index(name="count")
    )

    print(f"\n{col}")
    display(counts)

STATISTIC

       value  count
0   EHQ03C01   6216
1   EHQ03S10   6216
2    EHQ03S8   6216
3    EHQ03S7   6216
4    EHQ03S6   6216
5    EHQ03S5   6216
6    EHQ03S4   6216
7    EHQ03S3   6216
8    EHQ03S2   6216
9   EHQ03S11   6216
10  EHQ03C11   6216
11  EHQ03C02   6216
12  EHQ03C10   6216
13  EHQ03C09   6216
14  EHQ03C08   6216
15  EHQ03C07   6216
16  EHQ03C06   6216
17  EHQ03C05   6216
18  EHQ03C04   6216
19  EHQ03C03   6216
20   EHQ03S9   6216

Statistic Label

                                                value  count
0                      Average Hourly Benefit in Kind   6216
1   Average Hourly Total Labour Costs (Seasonally ...   6216
2   Average weekly earnings excluding irregular ea...   6216
3   Average weekly earnings excluding irregular ea...   6216
4   Average weekly earnings excluding irregular an...   6216
5   Average weekly earnings excluding irregular an...   6216
6     Average Weekly Paid Hours (Seasonally Adjusted)   6216
7                           Average Weekly Paid Hours   6216
8       Average Weekly Earnings (Seasonally Adjusted)   6216
9                             Average Weekly Earnings   6216
10                  Average Hourly Total Labour Costs   6216
11  Average Hourly Benefit in Kind (Seasonally Adj...   6216
12  Average Hourly Other Labour Costs (Seasonally ...   6216
13                  Average Hourly Other Labour Costs   6216
14  Average Hourly Irregular Earnings (Seasonally ...   6216
15                  Average Hourly Irregular Earnings   6216
16  Average Hourly Earnings excluding Irregular Ea...   6216
17  Average Hourly Earnings excluding Irregular Ea...   6216
18      Average Hourly Earnings (Seasonally Adjusted)   6216
19                            Average Hourly Earnings   6216
20                                         Employment   6216

TLIST(Q1)

    value  count
0   20081   1764
1   20214   1764
2   20212   1764
3   20211   1764
4   20204   1764
..    ...    ...
69  20141   1764
70  20134   1764
71  20133   1764
72  20132   1764
73  20262   1764

[74 rows x 2 columns]

Quarter

     value  count
0   2008Q1   1764
1   2021Q4   1764
2   2021Q2   1764
3   2021Q1   1764
4   2020Q4   1764
..     ...    ...
69  2014Q1   1764
70  2013Q4   1764
71  2013Q3   1764
72  2013Q2   1764
73  2026Q2   1764

[74 rows x 2 columns]

C02665V03225

    value  count
0       -   6216
1       N   6216
2   Y3500   6216
3   Y1900   6216
4   Y0900   6216
5       S   6216
6       R   6216
7       Q   6216
8       P   6216
9       O   6216
10      M   6216
11      B   6216
12      L   6216
13      K   6216
14      J   6216
15      I   6216
16      H   6216
17      G   6216
18      F   6216
19      C   6216
20  Y7400   6216

Economic Sector NACE Rev 2

                                                value  count
0       Accommodation and food service activities (I)   6216
1                                   Industry (B to E)   6216
2                      Transportation and storage (H)   6216
3                          Real estate activities (L)   6216
4   Public administration and defence; compulsory ...   6216
5   Professional, scientific and technical activit...   6216
6                        Other service activities (S)   6216
7                            Mining and quarrying (B)   6216
8                                   Manufacturing (C)   6216
9                   Information and communication (J)   6216
10        Human health and social work activities (Q)   6216
11  Administrative and support service activities (N)   6216
12  Financial, insurance and real estate activitie...   6216
13             Financial and insurance activities (K)   6216
14  Electricity, water supply and waste management...   6216
15                                      Education (P)   6216
16                                   Construction (F)   6216
17  Arts, entertainment, recreation and other serv...   6216
18             Arts, entertainment and recreation (R)   6216
19                          All NACE economic sectors   6216
20  Wholesale and retail trade; repair of motor ve...   6216

C02397V02888

  value  count
0     -  32634
1     1  32634
2     2  32634
3     3  32634

Type of Employee

                                               value  count
0                                      All employees  32634
1              Clerical, sales and service employees  32634
2  Managers, professionals and associated profess...  32634
3  Production, transport, craft and other manual ...  32634

UNIT

    value   count
0    Euro  111888
1   Hours   12432
2  Number    6216

In [12]:
for col in category_columns:
    missing_stats = (
        df.groupby(col, observed=True, dropna=False)["VALUE"]
        .agg(
            total_rows="size",
            valid_rows="count",
        )
    )

    missing_stats["missing_rows"] = (
        missing_stats["total_rows"] - missing_stats["valid_rows"]
    )
    missing_stats["missing_pct"] = (
        missing_stats["missing_rows"]
        .div(missing_stats["total_rows"])
        .mul(100)
        .round(2)
    )

    print(f"\n{col}")
    display(missing_stats.sort_values("missing_pct", ascending=False))

STATISTIC

           total_rows  valid_rows  missing_rows  missing_pct
STATISTIC
EHQ03S9          6216           0          6216       100.00
EHQ03S10         6216           0          6216       100.00
EHQ03S8          6216           0          6216       100.00
EHQ03S7          6216           0          6216       100.00
EHQ03S6          6216           0          6216       100.00
EHQ03S5          6216           0          6216       100.00
EHQ03S4          6216           0          6216       100.00
EHQ03S3          6216           0          6216       100.00
EHQ03S2          6216           0          6216       100.00
EHQ03S11         6216           0          6216       100.00
EHQ03C09         6216        1050          5166        83.11
EHQ03C11         6216        1554          4662        75.00
EHQ03C10         6216        1554          4662        75.00
EHQ03C01         6216        1807          4409        70.93
EHQ03C02         6216        2009          4207        67.68
EHQ03C08         6216        2009          4207        67.68
EHQ03C07         6216        2009          4207        67.68
EHQ03C06         6216        2009          4207        67.68
EHQ03C05         6216        2009          4207        67.68
EHQ03C04         6216        2009          4207        67.68
EHQ03C03         6216        2009          4207        67.68

Statistic Label

,total_rows,valid_rows,missing_rows,missing_pct
Statistic Label,,,,
Average Weekly Earnings (Seasonally Adjusted),6216,0,6216,100.00
Average weekly earnings excluding irregular earnings (Seasonally adjusted),6216,0,6216,100.00
Average Hourly Earnings (Seasonally Adjusted),6216,0,6216,100.00
Average Hourly Earnings excluding Irregular Earnings (Seasonally Adjusted),6216,0,6216,100.00
Average weekly earnings excluding irregular and overtime earnings (Seasonally adjusted),6216,0,6216,100.00
Average Hourly Irregular Earnings (Seasonally Adjusted),6216,0,6216,100.00
Average Hourly Other Labour Costs (Seasonally Adjusted),6216,0,6216,100.00
Average Hourly Benefit in Kind (Seasonally Adjusted),6216,0,6216,100.00
Average Hourly Total Labour Costs (Seasonally Adjusted),6216,0,6216,100.00
Average Weekly Paid Hours (Seasonally Adjusted),6216,0,6216,100.00
Average Hourly Benefit in Kind,6216,1050,5166,83.11
Average weekly earnings excluding irregular earnings,6216,1554,4662,75.00
Average weekly earnings excluding irregular and overtime earnings,6216,1554,4662,75.00
Employment,6216,1807,4409,70.93
Average Weekly Paid Hours,6216,2009,4207,67.68
Average Weekly Earnings,6216,2009,4207,67.68
Average Hourly Other Labour Costs,6216,2009,4207,67.68
Average Hourly Irregular Earnings,6216,2009,4207,67.68
Average Hourly Earnings excluding Irregular Earnings,6216,2009,4207,67.68
Average Hourly Earnings,6216,2009,4207,67.68
Average Hourly Total Labour Costs,6216,2009,4207,67.68

TLIST(Q1)

           total_rows  valid_rows  missing_rows  missing_pct
TLIST(Q1)
20172            1764         224          1540        87.30
20241            1764         224          1540        87.30
20163            1764         224          1540        87.30
20164            1764         224          1540        87.30
20171            1764         224          1540        87.30
...               ...         ...           ...          ...
20091            1764         616          1148        65.08
20082            1764         632          1132        64.17
20084            1764         632          1132        64.17
20083            1764         632          1132        64.17
20081            1764         632          1132        64.17

[74 rows x 4 columns]

Quarter

         total_rows  valid_rows  missing_rows  missing_pct
Quarter
2017Q2         1764         224          1540        87.30
2024Q1         1764         224          1540        87.30
2016Q3         1764         224          1540        87.30
2016Q4         1764         224          1540        87.30
2017Q1         1764         224          1540        87.30
...             ...         ...           ...          ...
2009Q1         1764         616          1148        65.08
2008Q2         1764         632          1132        64.17
2008Q4         1764         632          1132        64.17
2008Q3         1764         632          1132        64.17
2008Q1         1764         632          1132        64.17

[74 rows x 4 columns]

C02665V03225

              total_rows  valid_rows  missing_rows  missing_pct
C02665V03225
S                   6216         742          5474        88.06
R                   6216         742          5474        88.06
K                   6216         742          5474        88.06
L                   6216         742          5474        88.06
B                   6216         916          5300        85.26
C                   6216         946          5270        84.78
Y1900               6216         946          5270        84.78
-                   6216        1018          5198        83.62
P                   6216        1018          5198        83.62
Y3500               6216        1018          5198        83.62
Y0900               6216        1018          5198        83.62
Q                   6216        1018          5198        83.62
M                   6216        1018          5198        83.62
O                   6216        1018          5198        83.62
N                   6216        1018          5198        83.62
J                   6216        1018          5198        83.62
I                   6216        1018          5198        83.62
H                   6216        1018          5198        83.62
G                   6216        1018          5198        83.62
F                   6216        1018          5198        83.62
Y7400               6216        1018          5198        83.62

Economic Sector NACE Rev 2

,total_rows,valid_rows,missing_rows,missing_pct
Economic Sector NACE Rev 2,,,,
"Arts, entertainment and recreation (R)",6216,742,5474,88.06
Real estate activities (L),6216,742,5474,88.06
Financial and insurance activities (K),6216,742,5474,88.06
Other service activities (S),6216,742,5474,88.06
Mining and quarrying (B),6216,916,5300,85.26
"Electricity, water supply and waste management (D,E)",6216,946,5270,84.78
Manufacturing (C),6216,946,5270,84.78
Accommodation and food service activities (I),6216,1018,5198,83.62
Information and communication (J),6216,1018,5198,83.62
Transportation and storage (H),6216,1018,5198,83.62
Public administration and defence; compulsory social security (O),6216,1018,5198,83.62
"Professional, scientific and technical activities (M)",6216,1018,5198,83.62
Human health and social work activities (Q),6216,1018,5198,83.62
Industry (B to E),6216,1018,5198,83.62
Administrative and support service activities (N),6216,1018,5198,83.62
"Financial, insurance and real estate activities (K,L)",6216,1018,5198,83.62
Education (P),6216,1018,5198,83.62
Construction (F),6216,1018,5198,83.62
"Arts, entertainment, recreation and other service activities (R,S)",6216,1018,5198,83.62
All NACE economic sectors,6216,1018,5198,83.62
Wholesale and retail trade; repair of motor vehicles and motorcycles (G),6216,1018,5198,83.62

C02397V02888

              total_rows  valid_rows  missing_rows  missing_pct
C02397V02888
1                  32634        1141         31493        96.50
2                  32634        1141         31493        96.50
3                  32634        1156         31478        96.46
-                  32634       16590         16044        49.16

Type of Employee

,total_rows,valid_rows,missing_rows,missing_pct
Type of Employee,,,,
"Clerical, sales and service employees",32634,1141,31493,96.50
"Managers, professionals and associated professionals",32634,1141,31493,96.50
"Production, transport, craft and other manual workers",32634,1156,31478,96.46
All employees,32634,16590,16044,49.16

UNIT

        total_rows  valid_rows  missing_rows  missing_pct
UNIT
Euro        111888       16212         95676        85.51
Hours        12432        2009         10423        83.84
Number        6216        1807          4409        70.93